# Generated by Django 4.2.2 on 2023-10-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=15)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('room_type', models.CharField(max_length=35)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('guest_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=35)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('number_of_rooms', models.IntegerField()),
            ],
        ),
    ]
