# Generated by Django 4.2.2 on 2023-11-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=8)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=2)),
                ('room_type', models.CharField(max_length=35)),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='booking_ID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
